language: cpp
compiler:
  - gcc
before_install:
  - git submodule update --init --recursive
  - sudo apt-add-repository -y ppa:smspillaz/xorg-gtest
  - sudo apt-add-repository -y ppa:smspillaz/verapp-latest
  - sudo apt-get update -qq
  - sudo apt-get install -qq `cat DEPENDENCIES`
script:
  - mkdir build && cd build && cmake .. && make && ./tests/unit/uaw_unit_tests && ./tests/integration/uaw_integration_tests && ./tests/acceptance/uaw_acceptance_tests
